source("selection_helpers.R")
available <- c("Sample", "Condition", "Batch", "Subject", "Unused")
stopifnot(identical(table_s1_metadata_choices(available, c("Subject", "Condition", "Missing")), c("Subject", "Condition")))
stopifnot(identical(table_s1_metadata_choices(available, character(0)), character(0)))
stopifnot(identical(table_s1_metadata_choices(available, c("Subject", "Subject")), "Subject"))
stopifnot(identical(retain_metadata_choice("Subject", c("Condition", "Subject"), "Condition"), "Subject"))
stopifnot(identical(retain_metadata_choice("Unused", c("Condition", "Subject"), "Condition"), ""))
stopifnot(identical(retain_metadata_choice(NULL, c("Condition", "Subject"), "Condition"), "Condition"))
stopifnot(identical(retain_metadata_choice(NULL, character(0), "Condition"), ""))
remove_options <- proteomics_multiselect_options("Choose values")
stopifnot(identical(unlist(remove_options$plugins), "remove_button"))
stopifnot(identical(remove_options$placeholder, "Choose values"))
drag_remove_options <- proteomics_multiselect_options("Choose and reorder", drag = TRUE, create = FALSE)
stopifnot(identical(unlist(drag_remove_options$plugins), c("drag_drop", "remove_button")))
stopifnot(identical(drag_remove_options$create, FALSE))
cat("Table S1 metadata scope and selection tests passed.\n")
